apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-submission-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grade-submission-portal
  template:
    metadata:
      labels:
        app: grade-submission-portal
    spec:
      containers:
      - name: grade-submission-portal
        image: rslim087/grade-submission-portal
        env:
        - name: GRADE_SERVICE_HOST
          value: grade-submission-api
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5001