apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-submission-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grade-submission-portal
  template:
    metadata:
      labels:
        app: grade-submission-portal
    spec:
      containers:
        - name: grade-submission-portal
          image: rslim087/grade-submission-portal
          envFrom:
            - configMapRef:
                name: grade-submission-portal-config
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
          ports:
            - containerPort: 5001