apiVersion: apps/v1
kind: Deployment
metadata:
  name: record-submission-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: record-submission-api
  template:
    metadata:
      labels:
        app: record-submission-api
    spec:
      containers:
        - name: record-submission-api
          image: rslim087/record-submission-api
          resources:
            limits:
              memory: "500Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 5