apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: grades-http-server-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grades-http-server
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80