apiVersion: v1
kind: Pod
metadata:
  name: grade-submission-portal
  labels:
    app: grade-submission-portal
spec:
  containers:
  - name: grade-submission-portal
    image: rslim087/grade-submission-portal
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 5001