apiVersion: apps/v1
kind: Deployment
metadata: 
  name: profile-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-management
  template:
    metadata:
      labels:
        app: profile-management
    spec:
      containers:
      - name: profile-management
        image: rslim087/profile-management:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3003