replicaCount: 1

image:
  repository: mongo
  pullPolicy: IfNotPresent

service:
  name: mongodb
  type: ClusterIP
  port: 27017

resources:
  limits:
    memory: "512Mi"
    cpu: "1000m"

storage:
  size: "1Gi"
  mountPath: /data/db