apiVersion: v1
kind: ConfigMap
metadata:
  name: order-management-config
data:
  PRODUCT_INVENTORY_API_HOST: "http://product-inventory"
  PRODUCT_CATALOG_API_HOST: "http://product-catalog"
  SHIPPING_HANDLING_API_HOST: "http://shipping-and-handling"