apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-support-team
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-support-team
  template:
    metadata:
      labels:
        app: contact-support-team
    spec:
      containers:
      - name: contact-support-team
        image: rslim087/contact-support-team:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000