apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-management
  template:
    metadata:
      labels:
        app: order-management
    spec:
      containers:
      - name: order-management
        image: rslim087/order-management:1.0.0
        envFrom:
        - configMapRef:
            name: order-management-config
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 9090