apiVersion: v1
kind: Pod
metadata:
  name: ecommerce-ui
  labels:
    app: ecommerce-ui
spec:
  containers:
  - name: ecommerce-ui
    image: rslim087/ecommerce-ui
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 4000