apiVersion: v1
kind: Service
metadata:
  name: record-submission-api
spec:
  type: NodePort
  selector:
    app: record-submission-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31005